CREATE TABLE accounts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_name  VARCHAR(255) NOT NULL,
    balance     NUMERIC(19, 2) NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE transactions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id     BIGINT NOT NULL REFERENCES accounts (id),
    type           VARCHAR(255) NOT NULL
        CONSTRAINT transactions_type_check
        CHECK (type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER_IN', 'TRANSFER_OUT')),
    amount         NUMERIC(19, 2) NOT NULL,
    balance_after  NUMERIC(19, 2) NOT NULL,
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- Islem gecmisi sorgusu: where account_id = ? order by created_at desc, id desc
CREATE INDEX idx_transactions_account_created
    ON transactions (account_id, created_at DESC, id DESC);
