spring.application.name=wallet

spring.datasource.url=jdbc:postgresql://localhost:5432/wallet
spring.datasource.username=wallet
spring.datasource.password=wallet

# Gecici: tablolari entity'lerden otomatik uretir (sonra Flyway'e gecilebilir)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
